# API Keys (replace with your actual values from .env)
GOOGLE_SEARCH_API_KEY="AIzaSyBiC_tsCAmwmPA6zcqOFJgAHGRM4Th6IJA"
CSE_ID="800c584b1ca5f460a"
YOUTUBE_API_KEY="AIzaSyBiC_tsCAmwmPA6zcqOFJgAHGRM4Th6IJA"
PROJECT_ID = "verityindex-0-0-1"
LOCATION = "us-central1"
DEBUG_OUTPUTS = "true"
DEPLOYMENT_MODE = "research"
STORAGE_BACKEND = "local"

# Google Service Account (converted from JSON)
[gcp_service_account]
type = "service_account"
project_id = "verityindex-0-0-1"
private_key_id = "6a21e94ca0a31c17af8d201a7e52f62bfe6f2e97"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgPawRJL6FztbJ\nvjuIOWPSVCtG+6d/DQRURLxPCKH031McCvUXgcSYg2gxpyDzNcU67NmIU0Yws/pO\nhhiwaMam0N4Ekg+hAt13fqAIPVGOuiDQTV+COcwVHWP7LDJiimvJqQEvy9Annevj\nOnZV9DW02qQLH0lfx+4aUmeFQ7MkqeS8UuyOyEi2aqnHjj2X+RHaXbCk/kEvsXGq\nWicPMaxDZP+t9FpuF3NEEdRxttKn+ViGyXOr+PYj68w7AsxwrzIuvf5pnpDVXyqk\n+IdZkYBFhZOxI0VOvEbxp6QHpH7wdIDMDq/AleflAtn7F6j+N3dcYj1+7C60iumj\newGa3lHjAgMBAAECggEANQABBBCXtbFSqJqznRyCUESHpexBm8vF5Utwz2FHFDOz\njQBwzWweBuXb1iR1yQu9Zv6E+sq0WhKFVWiUDPEy12UZMgDPi41jjA0FSIRjj+Yv\nSUZ2MyADyO4WLjMRnTc0bJhqLJFokVnx9g/VqRtjkiSJAqbAAZ6iufEMjW71d0f2\nQE2vWSsUlNwnHh3IxUkr5hxbGGcHLKgGHr6ZhnwT1zd6Z2YH65KUUilpxU75qzMW\nW3kBA1J7alOmlZIjX9zNp762nDJWGqP8YhIUcrHS45a5HILWNFTXgQp9NE2ZhivQ\n6pOlblVvsZ+zdpP7mNvAjv7iX4FOMBQXNZNIvmgVFQKBgQDN9UDAlFqnLAkALss3\nV/aOAdEgWQE5CM/Z0qH0p8huKuHT2TB+ygtFb+z8xVr/V3Cna8E0zA9e+FnfdmzP\nvITW7rRZZ5M5ryBbINC5xgod20OrFXKNcHNMBWyK+N6BDV5oBZi4UeenNFGyqVxE\ns8YeaANmEsmSv5FiDDKAQLNMzwKBgQDHLMeYeQbSYbF1CffMgQxeSWQPCfmNibwU\ny6Kg69FnM/YFtDMfUqWgv8rf32qbIFcSQpLlPRZ0OH7Msfb6Q9aU8ow5S7Q86egp\nAYr+xgsDF2utplZwmsjKSlzcHtTZzeIgL/J8RZDN18jQXt2J0y5WoASez/aVxpft\nnyeZSfR2rQKBgQCJubR4U3yfh8npDmGke7ULV1mySPKRYjwkDD9zLHPSf+iN0xIj\n5xZMc8FFcvAcCivyORN1K/QnbOokjbvL2uP2GqANnT6Nd3eqmLIbWLxRJNwGXwxA\nWu8u6f2gnTWllPwJkZyDvXmsjUcIs0pZQuJ8WM/VBUE4WdRtfXyT2TBNbwKBgA8n\nLwBApO44lIGtAndCkihSORST07Ka+f4zB+pqRoIth9gjP4hwhz1Vmh+yJbAro7Q1\n8GsUXLL24V69Y2bi5l5qnZR2V/4SZaFJBsQfWRMhIwYRE555iDEruyjcB6GSclO0\nkiQ2PrAKbLK9pOkpcesRPYi/lakLdN+VLjQRVlH5AoGBAI4sf8p4Asbw8lkB7Xko\nIXvEj569LKw4COUY03+GMELGkCkn+3pBq7lBd2rWrYOkLeY8zoWqxwrbMcS9YScv\nbWGqbdyVh45hfpelI4iz4lYTpWqI21N6x905xWHChhk6rEl0OGledsL5YO9uEuv0\nli47BFdZQahLdQ2QI3zYHkiK\n-----END PRIVATE KEY-----\n"
client_email = "verityindex-sa-research@verityindex-0-0-1.iam.gserviceaccount.com"
client_id = "100999611098674545291"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/verityindex-sa-research%40verityindex-0-0-1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"